<a href="https://colab.research.google.com/github/Geringer13/Netology_pyda/blob/master/ML_Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.datasets.samples_generator import make_regression 
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import math
import cmath
import pylab
import pandas as pd
import numpy as np

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.datasets.samples_generator module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.datasets. Anything that cannot be imported from sklearn.datasets is now part of the private API.
  warnings.warn(message, FutureWarning)


Задание 1 - Логистическая регрессия

In [2]:
data = pd.read_csv('heart.csv')
data.head()

FileNotFoundError: ignored

In [0]:
x = data.drop('target', axis=1)
y = data.target

In [0]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=27)

In [0]:
model = LogisticRegression(solver='liblinear').fit(X_train, y_train)

In [0]:
model_pred = model.predict(X_test)

print(classification_report(y_test, model_pred))

              precision    recall  f1-score   support

           0       0.86      0.89      0.87        35
           1       0.90      0.88      0.89        41

    accuracy                           0.88        76
   macro avg       0.88      0.88      0.88        76
weighted avg       0.88      0.88      0.88        76



Задание 2 - линейная классификация

In [0]:
from sklearn import datasets
iris = datasets.load_iris()

In [128]:
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [0]:
x = iris.data[:100]
y = iris.target[:100]

In [192]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [169]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [148]:
hypothesis.shape

(100,)

In [0]:
# генерируем случайные данные
x, y = make_regression(n_samples=100, n_features=1, n_informative=1, 
                        random_state=0, noise=35)

In [4]:
m, n = np.shape(x)
m, n

(100, 1)

In [5]:
# преобразуем x к следующему виду
x = np.c_[ np.ones(m), x]
x[:5]

array([[ 1.        , -0.35955316],
       [ 1.        ,  0.97663904],
       [ 1.        ,  0.40234164],
       [ 1.        , -0.81314628],
       [ 1.        , -0.88778575]])

In [0]:
# шаг алгоритма
alpha = 0.01

In [0]:
def gradient_descent_2(alpha, x, y, numIterations):
    """
    Функция реализует алгоритм градиентного спуска. На каждом шаге выводится значение функции потерь
    """
    
    m = x.shape[0] # 100
    theta = np.ones(x.shape[1]) # [ 1.  1.] ВЕСА МОДЕЛИ!!!
    x_transpose = x.transpose() # транспонированная матрица x
    
    for iter in range(0, numIterations):
        hypothesis = 1 / (1 + np.exp(-np.dot(x,  theta)))
        
        loss = hypothesis - y
        J = -np.sum(y * np.log(hypothesis) + (1 - y) * np.log(1 - hypothesis))  # функция потерь
        
        print( "iter %s | J: %.3f" % (iter, J) )
                
        gradient = np.dot(x_transpose, loss) / m         
        theta = theta - alpha * gradient  # update
    
    return theta

In [234]:
%%time
theta = gradient_descent_2(alpha, x, y, 1000)

iter 0 | J: 507.103
iter 1 | J: 497.351
iter 2 | J: 487.600
iter 3 | J: 477.850
iter 4 | J: 468.099
iter 5 | J: 458.349
iter 6 | J: 448.600
iter 7 | J: 438.851
iter 8 | J: 429.102
iter 9 | J: 419.355
iter 10 | J: 409.608
iter 11 | J: 399.863
iter 12 | J: 390.119
iter 13 | J: 380.376
iter 14 | J: 370.636
iter 15 | J: 360.898
iter 16 | J: 351.164
iter 17 | J: 341.433
iter 18 | J: 331.706
iter 19 | J: 321.985
iter 20 | J: 312.270
iter 21 | J: 302.563
iter 22 | J: 292.865
iter 23 | J: 283.179
iter 24 | J: 273.507
iter 25 | J: 263.851
iter 26 | J: 254.216
iter 27 | J: 244.605
iter 28 | J: 235.023
iter 29 | J: 225.476
iter 30 | J: 215.971
iter 31 | J: 206.518
iter 32 | J: 197.125
iter 33 | J: 187.805
iter 34 | J: 178.571
iter 35 | J: 169.441
iter 36 | J: 160.431
iter 37 | J: 151.565
iter 38 | J: 142.865
iter 39 | J: 134.359
iter 40 | J: 126.075
iter 41 | J: 118.045
iter 42 | J: 110.301
iter 43 | J: 102.875
iter 44 | J: 95.800
iter 45 | J: 89.103
iter 46 | J: 82.811
iter 47 | J: 76.942
iter 4

In [0]:
print(theta)

[3.43236945e-02 4.43608480e+01]


In [0]:
loss

NameError: ignored