In [3]:
import numpy as np

In [23]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
n = int(input())
item = np.arange(n)[::-1]
print(item)

10
[9 8 7 6 5 4 3 2 1 0]


In [7]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
n = int(input())
n = np.arange(n)[::-1]
s = 0
matrix = np.full([5, 5], n)
print(matrix)
for x, b in enumerate(matrix):
    s += (b[x])
print(s)


5
[[4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]]
10


In [12]:
# Задание 3
# Решите систему уравнений:
#  x + 3y = 12
# 4x + 2y + z = 4
# 5y + 4z = -3

#  x + 3y + 0z = 12
# 4x + 2y + z = 4
# 0x + 5y + 4z = -3
from numpy import linalg
c = np.array( [ [1, 3, 0], [4, 2, 1], [0, 5, 4] ] )
d = np.array( [12, 4, -3] )
linalg.solve(c, d)
# np.allclose( np.dot(c, linalg.solve(c, d)), d )

array([ 0.46666667,  3.84444444, -5.55555556])