<a href="https://colab.research.google.com/github/Geringer13/Netology_pyda/blob/master/%D0%9F%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8_%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D1%85_%D0%B0%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2_Homework_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from scipy.optimize import approx_fprime
import math

### Задание 1: 
Посчитайте частные производные функций в точках
(как обычно, необходимо решение на бумажке или в LaTeX и на numpy):

1) $f(x,y)=2x^2y^3 + 1/x + y^2x + 7$ в точке $(1,2)$

2) $f(x,y)=x^2y - sin(xy) + cos(x^2) + 6y$

In [0]:
def func(x):
    "Coordinate vector `x` should be an array of size two."
    
    return 2 * x[0]**2 * x[1]**3 + 1 / x[0] + x[1]**2 * x[0] + 7

In [90]:
v = np.array([1, 2])

eps = np.sqrt(np.finfo(float).eps)
approx_fprime(v, func, [eps, eps])

array([35.00000024, 28.00000024])

In [0]:
def func(x):
    "Coordinate vector `x` should be an array of size two."
    return x[0]**2 * x[1] - math.asin(x[0] * x[1]) + math.acos(x[0]**2) + 6 * x[1]

In [0]:
x = np.array([0, 0])

eps = np.sqrt(np.finfo(float).eps)
approx_fprime(x ,func, [eps, eps])

array([-1.49011612e-08,  6.00000000e+00])

### Задание 2:

Градиентный спуск своими руками

In [0]:
import tensorflow as tf

In [0]:
def f(x):
    return (x[0]**2) + (x[1]**2) 

In [0]:
x = np.array([100, 200])
lr = 0.1

In [0]:
for i in range(100):

    # Calculate gradient
    eps = np.sqrt(np.finfo(float).eps)
    grad = approx_fprime(x, f, epsilon=eps)

    x = x - lr * grad


In [0]:
grad

array([5.09259042e-08, 1.01851802e-07])

In [0]:
print("Минимум достигается в: ", x)
print("Значение функции в минимуме: ", f(x))

Минимум достигается в:  [1.29197811e-08 3.32901401e-08]
Значение функции в минимуме:  1.2751541739575636e-15


Проверка с помощью встроенной функции numpy: 

In [0]:
j = np.gradient(x)
j

array([2.03703591e-08, 2.03703591e-08])